services:
  audio-app:
    build:
      context: app
      dockerfile: Dockerfile
    container_name: GRAiS-app-container
    environment:
      - DISPLAY=$DISPLAY
      - PULSE_SERVER=unix:/mnt/wslg/PulseServer  # Use WSLg's PulseAudio server
    volumes:
      - /mnt/wslg:/mnt/wslg  # Map WSLg's PulseAudio server socket
      - /tmp/.X11-unix:/tmp/.X11-unix  # Allow X11 for GUI apps (if needed)
      - ~/.config/pulse/cookie:/root/.config/pulse/cookie  # PulseAudio authentication cookie
    network_mode: "host"  # Necessary for sound routing
